import type { SchemaField } from '~/types'
import { TYPE_SIZES } from '~/types'

const CPP_TYPE: Record<string, string> = {
  float32: 'float',
  int32: 'int32_t',
  uint8: 'uint8_t',
  boolean: 'uint8_t',
  flags: 'uint8_t',
}

function schemaByteLength(fields: SchemaField[]) {
  return fields.reduce((sum, f) => sum + (TYPE_SIZES[f.type] || 0), 0)
}

function sanitizeIdent(name: string, fallback: string) {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_')
  if (!cleaned || !/^[A-Za-z_]/.test(cleaned)) return fallback
  return cleaned
}

function flagMaskDefines(field: SchemaField): string[] {
  if (field.type !== 'flags' || !Array.isArray(field.bits)) return []
  const group = sanitizeIdent(field.name.toUpperCase(), 'FLAGS')
  return field.bits.map((bit) => {
    const flag = sanitizeIdent(bit.name.toUpperCase(), 'BIT')
    return `#define ${group}_${flag} (1u << ${Number(bit.bit)})`
  })
}

function fieldStructLine(f: SchemaField): string {
  const name = sanitizeIdent(f.name || 'unnamed', 'unnamed')
  if (f.type === 'flags') {
    return `  uint8_t ${name}; // packed flags (see masks below)`
  }
  const ctype = CPP_TYPE[f.type] || 'uint8_t'
  const note = f.type === 'boolean' ? ' // boolean 0/1' : ` // ${f.type}`
  return `  ${ctype} ${name};${note}`
}

function fieldPreviewLine(f: SchemaField): string {
  if (f.type === 'flags') {
    return `  uint8_t ${f.name || 'unnamed'}; // flags`
  }
  return `  ${CPP_TYPE[f.type] || 'uint8_t'} ${f.name || 'unnamed'};`
}

/**
 * Generate a downloadable ESP32-ready header for the packed telemetry struct.
 * Flags use a backing uint8_t plus #define masks — not compiler bitfields.
 */
export function useCppHeader() {
  function generateCppHeader(opts: {
    deviceName: string
    version: number
    fields: SchemaField[]
    encryptionEnabled?: boolean
  }): string {
    const version = Math.max(1, Math.min(255, opts.version | 0))
    const guard = sanitizeIdent(
      `STRUCT_${opts.deviceName.toUpperCase()}_V${version}_H`,
      `STRUCT_PACKET_V${version}_H`,
    )
    const structName = sanitizeIdent(
      `${opts.deviceName.replace(/\s+/g, '_')}_Packet_v${version}`,
      `TelemetryPacket_v${version}`,
    )
    const byteLen = schemaByteLength(opts.fields)

    const fieldLines = opts.fields.length
      ? opts.fields.map(fieldStructLine)
      : ['  // add fields…']

    const maskLines = opts.fields.flatMap(flagMaskDefines)

    const encNote = opts.encryptionEnabled
      ? [
          ' * Encrypted wire (ChaCha20-Poly1305) inside Protocol v2 payload:',
          ' *   [1B proto=2][16B key_id][1B SCHEMA_VERSION][4B ts][12B nonce]',
          ' *   [ciphertext = 4B uint32 LE unix_ts + Packet][16B tag][32B hmac]',
        ]
      : [
          ' * Protocol v2 plaintext payload:',
          ' *   [1B proto=2][16B key_id][1B SCHEMA_VERSION][4B ts][12B nonce]',
          ' *   [Packet bytes…][32B hmac]',
        ]

    return [
      `/* Auto-generated by Struct — do not hand-edit field layout */`,
      `#ifndef ${guard}`,
      `#define ${guard}`,
      ``,
      `#include <stdint.h>`,
      ``,
      `/* Wire schema version byte — must match schemas.version / packet header */`,
      `#define STRUCT_SCHEMA_VERSION  ((uint8_t)${version})`,
      `#define STRUCT_PACKET_SIZE     (${byteLen}u)`,
      ``,
      ...(maskLines.length
        ? ['/* Packed flags masks (backing field is uint8_t in the struct) */', ...maskLines, ``]
        : []),
      `/*`,
      ...encNote,
      ` */`,
      `#pragma pack(push, 1)`,
      `struct ${structName} {`,
      ...fieldLines,
      `};`,
      `#pragma pack(pop)`,
      ``,
      `#ifdef __cplusplus`,
      `static_assert(sizeof(${structName}) == STRUCT_PACKET_SIZE, "Unexpected packed size");`,
      `#endif`,
      ``,
      `#endif /* ${guard} */`,
      ``,
    ].join('\n')
  }

  function downloadCppHeader(filename: string, contents: string) {
    const blob = new Blob([contents], { type: 'text/x-c' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  function headerFilename(deviceName: string, version: number) {
    const base = sanitizeIdent(deviceName.toLowerCase().replace(/\s+/g, '_'), 'device')
    return `struct_${base}_v${version}.h`
  }

  function cppPreview(fields: SchemaField[], version: number, byteLength: number) {
    if (!fields.length) {
      return `#pragma pack(push, 1)\nstruct Packet {\n  // add fields…\n};\n#pragma pack(pop)`
    }
    const lines = fields.map(fieldPreviewLine)
    const masks = fields.flatMap(flagMaskDefines)
    return [
      `#define STRUCT_SCHEMA_VERSION ${version}`,
      ...(masks.length ? masks : []),
      `#pragma pack(push, 1)`,
      `struct Packet {`,
      ...lines,
      `};`,
      `#pragma pack(pop)`,
      `// sizeof(Packet) == ${byteLength}`,
      `// Wire: Protocol v2 [proto][key_id][version=${version}][ts][nonce][payload][hmac]`,
    ].join('\n')
  }

  return {
    generateCppHeader,
    downloadCppHeader,
    headerFilename,
    cppPreview,
    schemaByteLength,
  }
}
