import type { SchemaField } from '~/types'
import { TYPE_SIZES } from '~/types'

const CPP_TYPE: Record<string, string> = {
  float32: 'float',
  int32: 'int32_t',
  uint8: 'uint8_t',
  boolean: 'uint8_t',
}

function schemaByteLength(fields: SchemaField[]) {
  return fields.reduce((sum, f) => sum + (TYPE_SIZES[f.type] || 0), 0)
}

function sanitizeIdent(name: string, fallback: string) {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_')
  if (!cleaned || !/^[A-Za-z_]/.test(cleaned)) return fallback
  return cleaned
}

/**
 * Generate a downloadable ESP32-ready header for the packed telemetry struct.
 */
export function useCppHeader() {
  function generateCppHeader(opts: {
    deviceName: string
    version: number
    fields: SchemaField[]
    encryptionEnabled?: boolean
  }): string {
    const version = Math.max(1, Math.min(255, opts.version | 0))
    const guard = sanitizeIdent(
      `STRUCT_${opts.deviceName.toUpperCase()}_V${version}_H`,
      `STRUCT_PACKET_V${version}_H`,
    )
    const structName = sanitizeIdent(
      `${opts.deviceName.replace(/\s+/g, '_')}_Packet_v${version}`,
      `TelemetryPacket_v${version}`,
    )
    const byteLen = schemaByteLength(opts.fields)

    const fieldLines = opts.fields.length
      ? opts.fields.map((f) => {
          const ctype = CPP_TYPE[f.type] || 'uint8_t'
          const name = sanitizeIdent(f.name || 'unnamed', 'unnamed')
          const note = f.type === 'boolean' ? ' // boolean 0/1' : ` // ${f.type}`
          return `  ${ctype} ${name};${note}`
        })
      : ['  // add fields…']

    const encNote = opts.encryptionEnabled
      ? [
          ' * Encrypted wire (ChaCha20-Poly1305):',
          ' *   [16B api_key][1B SCHEMA_VERSION][12B nonce]',
          ' *   [ciphertext = 4B uint32 LE unix_ts + Packet][16B tag]',
        ]
      : [
          ' * Plaintext wire:',
          ' *   [16B api_key][1B SCHEMA_VERSION][Packet bytes…]',
        ]

    return [
      `/* Auto-generated by Struct — do not hand-edit field layout */`,
      `#ifndef ${guard}`,
      `#define ${guard}`,
      ``,
      `#include <stdint.h>`,
      ``,
      `/* Wire schema version byte — must match schemas.version / packet header */`,
      `#define STRUCT_SCHEMA_VERSION  ((uint8_t)${version})`,
      `#define STRUCT_PACKET_SIZE     (${byteLen}u)`,
      ``,
      `/*`,
      ...encNote,
      ` */`,
      `#pragma pack(push, 1)`,
      `struct ${structName} {`,
      ...fieldLines,
      `};`,
      `#pragma pack(pop)`,
      ``,
      `#ifdef __cplusplus`,
      `static_assert(sizeof(${structName}) == STRUCT_PACKET_SIZE, "Unexpected packed size");`,
      `#endif`,
      ``,
      `#endif /* ${guard} */`,
      ``,
    ].join('\n')
  }

  function downloadCppHeader(filename: string, contents: string) {
    const blob = new Blob([contents], { type: 'text/x-c' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  function headerFilename(deviceName: string, version: number) {
    const base = sanitizeIdent(deviceName.toLowerCase().replace(/\s+/g, '_'), 'device')
    return `struct_${base}_v${version}.h`
  }

  function cppPreview(fields: SchemaField[], version: number, byteLength: number) {
    if (!fields.length) {
      return `#pragma pack(push, 1)\nstruct Packet {\n  // add fields…\n};\n#pragma pack(pop)`
    }
    const lines = fields.map((f) => {
      return `  ${CPP_TYPE[f.type] || 'uint8_t'} ${f.name || 'unnamed'};`
    })
    return [
      `#define STRUCT_SCHEMA_VERSION ${version}`,
      `#pragma pack(push, 1)`,
      `struct Packet {`,
      ...lines,
      `};`,
      `#pragma pack(pop)`,
      `// sizeof(Packet) == ${byteLength}`,
      `// Wire: [16B api_key][1B version=${version}][payload]`,
    ].join('\n')
  }

  return {
    generateCppHeader,
    downloadCppHeader,
    headerFilename,
    cppPreview,
    schemaByteLength,
  }
}
