import type {SchemaField} from '../app/types'
import {generateSchemaCode,type CodeLanguage} from './schemaCodegen'
/** No device credentials or IDs are accepted by this generator. */
export function generateSchemaProject(fields:SchemaField[],version:number,language:CodeLanguage,encrypted=false):Record<string,string>{
 const code=generateSchemaCode(fields,version,language,encrypted),files:Record<string,string>={}
 files['schema.json']=JSON.stringify(fields,null,2)
 files['README.md']=`# Struct ${language} starter\n\nSchema version ${version}. The encoder matches the saved schema. Example values are zero/false; replace them with sensor readings.\n\nSDK source is included beside this project under ../struct-sdk. It is a release candidate, not hardware qualification. See ../docs/SDK-SUPPORT.md and platform integration guides. Never commit credentials.\n\nConfigure STRUCT_HOST, STRUCT_PORT (default 8081), STRUCT_KEY_ID and STRUCT_API_SECRET in your environment. ${encrypted?'Encryption is required: set STRUCT_ENCRYPTION_KEY to the separate 64-hex encryption key.':'Encryption is off for this schema export.'}\n`
 if(language==='JavaScript'){
  files[code.filename]=code.source
  const values=fields.map(f=>`${JSON.stringify(f.name)}: ${f.type==='char'?`new Uint8Array(${f.length})`:f.type==='boolean'?'false':f.type==='flags'?'{}':'0'}`).join(', ')
  files['main.mjs']=`import {createRequire} from 'node:module';\nimport {pack,SCHEMA_VERSION} from './${code.filename}';\nconst {StructClient}=createRequire(import.meta.url)('../struct-sdk/js/index.cjs');\nconst client=new StructClient({host:process.env.STRUCT_HOST,port:Number(process.env.STRUCT_PORT||8081),keyId:process.env.STRUCT_KEY_ID,apiSecret:process.env.STRUCT_API_SECRET${encrypted?',encryptionKey:process.env.STRUCT_ENCRYPTION_KEY':''}});\n${encrypted?"if(!process.env.STRUCT_ENCRYPTION_KEY)throw new Error('Encryption key required');\n":''}console.log(await client.send(SCHEMA_VERSION,Buffer.from(pack({${values}})),{confirmed:true}));\n`
  files['README.md']+='\nRun `node main.mjs` (Node 20+).\n'
 }else if(language==='Python'){
  files[code.filename]=code.source
  const values=fields.map(f=>`${JSON.stringify(f.name)}: ${f.type==='char'?`bytes(${f.length})`:f.type==='boolean'?'False':f.type==='flags'?'{}':'0'}`).join(', ')
  files['main.py']=`import os, sys\nfrom pathlib import Path\nsys.path.insert(0,str(Path(__file__).resolve().parents[1]/'struct-sdk'/'python'))\nfrom struct_device import StructClient\nfrom ${code.filename.slice(0,-3)} import pack, SCHEMA_VERSION\nclient=StructClient(os.environ['STRUCT_HOST'],os.environ['STRUCT_KEY_ID'],os.environ['STRUCT_API_SECRET'],int(os.getenv('STRUCT_PORT','8081'))${encrypted?",encryption_key=os.environ['STRUCT_ENCRYPTION_KEY']":''})\nprint(client.send(SCHEMA_VERSION,pack({${values}}),confirmed=True))\n`
  files['README.md']+='\nRun `python -m pip install "../struct-sdk/python[encryption]"`, then `python main.py`. Use a numeric IPv4 host.\n'
 }else if(language==='Rust'){
  files['src/packet.rs']=code.source
  files['Cargo.toml']='[package]\nname="struct-starter"\nversion="0.1.0"\nedition="2021"\n[dependencies]\nstruct-device={path="../struct-sdk/rust"}\n'
  const values=fields.map(f=>`f_${f.name}: ${f.type==='char'?`[0;${f.length}]`:f.type==='boolean'?'false':f.type==='float32'?'0.0':'0'}`).join(', ')
  files['src/main.rs']=`mod packet;\nuse struct_device::{Client,Delivery};\nfn main()->Result<(),Box<dyn std::error::Error>>{\nlet endpoint=format!("{}:{}",std::env::var("STRUCT_HOST")?,std::env::var("STRUCT_PORT").unwrap_or("8081".into())).parse()?;\nlet mut client=Client::new(endpoint,&std::env::var("STRUCT_KEY_ID")?,&std::env::var("STRUCT_API_SECRET")?)?;\n${encrypted?'client.set_encryption_hex(&std::env::var("STRUCT_ENCRYPTION_KEY")?)?;\n':''}let packet=packet::StructPacket{${values}};\nprintln!("{:?}",client.send(packet::SCHEMA_VERSION,&packet.pack(),Delivery{confirmed:true,..Delivery::default()},None)?.status);\nOk(())\n}\n`
  files['README.md']+='\nRun `cargo run`. Use a numeric IP endpoint.\n'
 }else if(language==='Arduino'){
  files[code.filename]=code.source
  files['project.ino']=`#include <WiFi.h>\n#include <StructEsp32.h>\n#include "${code.filename}"\n#include "credentials.h"\nStructEsp32 client; bool waiting=false; uint32_t nextSample=0;\nvoid setup(){\nWiFi.begin(WIFI_SSID,WIFI_PASSWORD);\nuint32_t started=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-started<15000)delay(50);\nconfigTime(0,0,"pool.ntp.org");\nstarted=millis();while(time(nullptr)<1577836800&&millis()-started<10000)delay(50);\nclient.begin(GATEWAY_IP,8081,STRUCT_KEY_ID,STRUCT_API_SECRET);\n${encrypted?'client.encryptionHex(STRUCT_ENCRYPTION_KEY);\n':''}}\nvoid loop(){\nif(waiting){if(client.poll()!=STRUCT_PENDING){waiting=false;nextSample=millis()+60000;}}\nelse if((int32_t)(millis()-nextSample)>=0){StructPacket values={};uint8_t bytes[STRUCT_PACKET_SIZE];struct_pack_packet(bytes,sizeof(bytes),&values);waiting=client.send(STRUCT_SCHEMA_VERSION,bytes,sizeof(bytes),struct_delivery_default(1))==STRUCT_PENDING;if(!waiting)nextSample=millis()+60000;}delay(5);\n}\n`
  files['credentials.example.h']='#define WIFI_SSID "replace"\n#define WIFI_PASSWORD "replace"\n#define GATEWAY_IP IPAddress(127,0,0,1)\n#define STRUCT_KEY_ID "replace"\n#define STRUCT_API_SECRET "replace"\n#define STRUCT_ENCRYPTION_KEY "replace"\n'
  files['README.md']+='\nInstall ../struct-sdk/c as the Struct Arduino library. Copy credentials.example.h to credentials.h and configure the LAN gateway address (127.0.0.1 is only a placeholder). Open project.ino in Arduino ESP32. Inspect delivery outcomes before putting hardware to sleep.\n'
 }else{
  files[code.filename]=code.source
  const ext=language==='C++'?'cpp':'c'
  files[`main.${ext}`]=`#define _POSIX_C_SOURCE 200809L\n#include <stdio.h>\n#include <stdlib.h>\n#include <time.h>\n#include "struct_posix.h"\n#include "${code.filename}"\nstatic uint32_t now_ms(void){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return (uint32_t)((uint64_t)t.tv_sec*1000+t.tv_nsec/1000000);}\nint main(void){\nstruct_posix transport;struct_port port;struct_client client;StructPacket values={0};uint8_t bytes[STRUCT_PACKET_SIZE];\nconst char *service=getenv("STRUCT_PORT");if(struct_posix_open(&transport,&port,getenv("STRUCT_HOST"),service?service:"8081"))return 1;\nif(struct_init(&client,&port,getenv("STRUCT_KEY_ID"),getenv("STRUCT_API_SECRET"))!=STRUCT_IDLE){struct_posix_close(&transport);return 1;}\n${encrypted?'if(!getenv("STRUCT_ENCRYPTION_KEY")||struct_set_encryption_hex(&client,getenv("STRUCT_ENCRYPTION_KEY"))!=STRUCT_IDLE){struct_clear(&client);struct_posix_close(&transport);return 1;}\n':''}struct_pack_packet(bytes,sizeof(bytes),&values);\nstruct_result result=struct_send(&client,STRUCT_SCHEMA_VERSION,bytes,sizeof(bytes),(uint32_t)time(NULL),now_ms(),struct_delivery_default(1));\nwhile(result==STRUCT_PENDING){struct timespec pause={0,10000000};nanosleep(&pause,NULL);result=struct_poll(&client,now_ms());}\nprintf("delivery status: %d\\n",(int)result);struct_clear(&client);struct_posix_close(&transport);return result==STRUCT_COMMITTED?0:1;\n}\n`
  files['CMakeLists.txt']=`cmake_minimum_required(VERSION 3.16)\nproject(struct_starter C CXX)\nadd_subdirectory(../struct-sdk/c sdk-build)\nfind_library(MBEDCRYPTO mbedcrypto REQUIRED)\nadd_executable(telemetry main.${ext} ../struct-sdk/c/ports/struct_posix.c)\ntarget_include_directories(telemetry PRIVATE ../struct-sdk/c/ports)\ntarget_link_libraries(telemetry PRIVATE struct_sdk mbedcrypto)\n`
  files['README.md']+='\nPOSIX host example: install mbedTLS development headers, run `cmake -S . -B build && cmake --build build`, then `./build/telemetry`. Firmware uses the same encoder with the ESP-IDF, Zephyr or STM32 adapter.\n'
 }
 files['.gitignore']='credentials.h\n.env\nbuild/\ntarget/\n__pycache__/\n'
 return files
}
