/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function schemaByteLength(schemaJson: string): number
export declare function parsePayload(payload: Buffer, schemaJson: string): any
export declare function encodePayload(valuesJson: string, schemaJson: string): Buffer
